import {
  UserData,
  CsvUploadData,
  FraudRuleData,
  PanelistData,
  PanelistFlagData,
} from './definitions';

export const placeholderUsers: UserData[] = [
  {
    full_name: 'Carlos Medina',
    email: 'admin@example.com',
    password: 'Password123!',
    role: 'admin',
  },
];

export const placeholderCsvUploads: CsvUploadData[] = [
  {
    project_name: 'Q3 Cardiology Panel Audit',
    company_name: 'HealthData Corp',
    upload_year: 2026,
    raw_file_path: '/uploads/raw/q3_cardio_2026.csv',
    file_size_bytes: 204800,
    initial_participant_count: 50,
    fraudulent_participant_count: 10,
  },
];

export const placeholderFraudRules: FraudRuleData[] = [
  {
    rule_code: 'NPI_INVALID',
    rule_name: 'Invalid NPI Checksum',
    category: 'npi_check',
    description: 'NPI number fails 10-digit Luhn algorithm validation.',
    risk_score_weight: 25.0,
    severity_level: 'high',
    is_active: true,
  },
];



export const placeholderPanelists: PanelistData[] = [
  // 1. Valid / Normal Panelists (Local IP matching practice region)
  {
    first_name: 'John',
    last_name: 'Doe',
    email: 'johndoe@example.com',
    phone_number: '555-0101',
    npi_number: '1234567890',
    specialty: 'Cardiology',
    practice_name: 'Austin Heart Center',
    street_address: '123 Main St',
    city: 'Austin',
    state: 'TX',
    postal_code: '78701',
    ip_address: '24.227.128.1', // Texas area public IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Sarah',
    last_name: 'Connor',
    email: 'sconnor@example.com',
    phone_number: '555-0102',
    npi_number: '2345678901',
    specialty: 'Neurology',
    practice_name: 'NY Neurological Clinic',
    street_address: '450 5th Ave',
    city: 'New York',
    state: 'NY',
    postal_code: '10018',
    ip_address: '8.8.8.8', // NY / East Coast public IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Michael',
    last_name: 'Scott',
    email: 'mscott@example.com',
    phone_number: '555-0103',
    npi_number: '3456789012',
    specialty: 'Internal Medicine',
    practice_name: 'Scranton Health Associates',
    street_address: '1720 Lackawanna Ave',
    city: 'Scranton',
    state: 'PA',
    postal_code: '18503',
    ip_address: '66.102.0.0', // PA region public IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Emily',
    last_name: 'Watson',
    email: 'ewatson@example.com',
    phone_number: '555-0104',
    npi_number: '4567890123',
    specialty: 'Pediatrics',
    practice_name: 'Bay Childrens Health',
    street_address: '500 Parnassus Ave',
    city: 'San Francisco',
    state: 'CA',
    postal_code: '94143',
    ip_address: '1.1.1.1', // West Coast public IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Robert',
    last_name: 'Chen',
    email: 'rchen@example.com',
    phone_number: '555-0105',
    npi_number: '5678901234',
    specialty: 'Dermatology',
    practice_name: 'Chicago Skin Institute',
    street_address: '233 S Wacker Dr',
    city: 'Chicago',
    state: 'IL',
    postal_code: '60606',
    ip_address: '50.200.0.1', // Midwest public IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },

  // 2. Distance Mismatch (>300 miles via Haversine)
  {
    first_name: 'David',
    last_name: 'Miller',
    email: 'dmiller@example.com',
    phone_number: '555-0106',
    npi_number: '6789012345',
    specialty: 'Orthopedic Surgery',
    practice_name: 'Beverly Hills Orthopedics',
    street_address: '9400 Wilshire Blvd',
    city: 'Beverly Hills',
    state: 'CA',
    postal_code: '90212',
    ip_address: '8.8.8.8', // New York IP vs California Practice (~2,400 miles)
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Jessica',
    last_name: 'Taylor',
    email: 'jtaylor@example.com',
    phone_number: '555-0107',
    npi_number: '7890123456',
    specialty: 'Oncology',
    practice_name: 'Miami Cancer Care',
    street_address: '1500 NW 12th Ave',
    city: 'Miami',
    state: 'FL',
    postal_code: '33136',
    ip_address: '1.1.1.1', // West Coast IP vs Florida Practice (~2,500 miles)
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'James',
    last_name: 'Wilson',
    email: 'jwilson@example.com',
    phone_number: '555-0108',
    npi_number: '8901234567',
    specialty: 'Gastroenterology',
    practice_name: 'Seattle Digestive Health',
    street_address: '1100 9th Ave',
    city: 'Seattle',
    state: 'WA',
    postal_code: '98101',
    ip_address: '24.227.128.1', // Texas IP vs Washington Practice (~1,700 miles)
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Amanda',
    last_name: 'White',
    email: 'awhite@example.com',
    phone_number: '555-0109',
    npi_number: '9012345678',
    specialty: 'Psychiatry',
    practice_name: 'Denver Behavioral Center',
    street_address: '777 Bannock St',
    city: 'Denver',
    state: 'CO',
    postal_code: '80204',
    ip_address: '71.198.0.1', // Florida IP vs Colorado Practice (~1,700 miles)
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Brian',
    last_name: 'Martinez',
    email: 'bmartinez@example.com',
    phone_number: '555-0110',
    npi_number: '0123456789',
    specialty: 'Urology',
    practice_name: 'Boston Urology Associates',
    street_address: '75 Francis St',
    city: 'Boston',
    state: 'MA',
    postal_code: '02115',
    ip_address: '50.200.0.1', // Illinois IP vs Massachusetts Practice (~850 miles)
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },

  // 3. Known Proxy / VPN / Tor Node IPs
  {
    first_name: 'Karen',
    last_name: 'Page',
    email: 'kpage@example.com',
    phone_number: '555-0111',
    npi_number: '1122334455',
    specialty: 'Endocrinology',
    practice_name: 'Manhattan Medical Group',
    street_address: '100 E 77th St',
    city: 'New York',
    state: 'NY',
    postal_code: '10075',
    ip_address: '81.2.69.142', // Known Tor exit node
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Leonard',
    last_name: 'Hofstadter',
    email: 'lhofstadter@example.com',
    phone_number: '555-0112',
    npi_number: '2233445566',
    specialty: 'Pulmonology',
    practice_name: 'Pasadena Respiratory Health',
    street_address: '100 W California Blvd',
    city: 'Pasadena',
    state: 'CA',
    postal_code: '91105',
    ip_address: '1.1.1.1', // Known Proxy/VPN IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Rachel',
    last_name: 'Green',
    email: 'rgreen@example.com',
    phone_number: '555-0113',
    npi_number: '3344556677',
    specialty: 'Rheumatology',
    practice_name: 'Atlanta Joint & Spine',
    street_address: '550 Peachtree St NE',
    city: 'Atlanta',
    state: 'GA',
    postal_code: '30308',
    ip_address: '118.143.21.1', // Known Proxy/VPN IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Christopher',
    last_name: 'Moltisanti',
    email: 'cmoltisanti@example.com',
    phone_number: '555-0114',
    npi_number: '4455667788',
    specialty: 'Anesthesiology',
    practice_name: 'Jersey Shore Surgical',
    street_address: '1945 Route 33',
    city: 'Neptune',
    state: 'NJ',
    postal_code: '07753',
    ip_address: '24.227.128.1', // Known Proxy/VPN IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Pamela',
    last_name: 'Beesly',
    email: 'pbeesly@example.com',
    phone_number: '555-0115',
    npi_number: '5566778899',
    specialty: 'Ophthalmology',
    practice_name: 'Keystone Eye Center',
    street_address: '300 Meadow Ave',
    city: 'Scranton',
    state: 'PA',
    postal_code: '18505',
    ip_address: '200.105.128.1', // Known Proxy/VPN IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },

  // 4. Foreign Country IP Mismatch
  {
    first_name: 'Peter',
    last_name: 'Parker',
    email: 'pparker@example.com',
    phone_number: '555-0116',
    npi_number: '6677889900',
    specialty: 'Nephrology',
    practice_name: 'Queens Kidney Clinic',
    street_address: '56-45 Main St',
    city: 'Flushing',
    state: 'NY',
    postal_code: '11355',
    ip_address: '81.2.69.142', // United Kingdom IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Bruce',
    last_name: 'Wayne',
    email: 'bwayne@example.com',
    phone_number: '555-0117',
    npi_number: '7788990011',
    specialty: 'Emergency Medicine',
    practice_name: 'Gotham Trauma Center',
    street_address: '100 Medical Center Way',
    city: 'Chicago',
    state: 'IL',
    postal_code: '60611',
    ip_address: '200.105.128.1', // Latin America IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Clark',
    last_name: 'Kent',
    email: 'ckent@example.com',
    phone_number: '555-0118',
    npi_number: '8899001122',
    specialty: 'Family Medicine',
    practice_name: 'Metropolis Health',
    street_address: '400 E 51st St',
    city: 'Kansas City',
    state: 'MO',
    postal_code: '64110',
    ip_address: '118.143.21.1', // Asia-Pacific IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Diana',
    last_name: 'Prince',
    email: 'dprince@example.com',
    phone_number: '555-0119',
    npi_number: '9900112233',
    specialty: 'Pathology',
    practice_name: 'Capitol Pathology Lab',
    street_address: '2001 Georgia Ave NW',
    city: 'Washington',
    state: 'DC',
    postal_code: '20060',
    ip_address: '81.2.69.143', // European IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
  {
    first_name: 'Tony',
    last_name: 'Stark',
    email: 'tstark@example.com',
    phone_number: '555-0120',
    npi_number: '0011223344',
    specialty: 'Radiology',
    practice_name: 'Malibu Imaging Center',
    street_address: '23805 Stuart Ranch Rd',
    city: 'Malibu',
    state: 'CA',
    postal_code: '90265',
    ip_address: '200.105.128.2', // South America IP
    risk_score: 0.0,
    risk_level: 'low',
    review_status: 'pending',
  },
];

export const placeholderPanelistFlags: PanelistFlagData[] = [
  {
    rule_code: 'NPI_INVALID',
    explanation: 'Provided NPI failed Luhn validation during automatic check.',
  },
];